services:
  postgres:
    container_name: postgres-sql-book
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DATA: /var/lib/postgresql/data
      POSTGRES_DB: book_social_db

    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-book
    image: maildev/maildev
    ports:
      - 1080:1080

networks:
  spring-demo:
    driver: bridge

volumes:
  postgres:
    driver: local